version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 0
    groups:
      security:
        applies-to: security-updates
        patterns:
          - "*"
    commit-message:
      prefix: "deps"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 0
    groups:
      actions:
        applies-to: security-updates
        patterns:
          - "*"
    commit-message:
      prefix: "ci"
